# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

opt_out_usage

default_platform(:ios)

platform :ios do
  desc "Build with connect"
  lane :connect do
    setup_ci if ENV['CI']
    import_certificate(
      certificate_path: "./certificate.p12",
      certificate_password: ENV["CERTIFICATE_PASSWORD"]
    )
    api_key = app_store_connect_api_key(
      key_id: "VG8XUGYMD6",
      issuer_id: "69a6de85-d476-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./AuthKey_VG8XUGYMD6.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    # get_certificates(api_key: api_key)
    get_provisioning_profile(filename: "App.mobileprovision")
    build_app(scheme: "Demo")
  end

  lane :tests do
  run_tests(project: "Demo.xcodeproj",
            devices: ["iPhone 12 mini"],
            scheme: "Demo")
  end

  desc "Build app"
  lane :build do
    build_app(scheme: "Demo")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    increment_build_number(xcodeproj: "Demo.xcodeproj")
    build_app(scheme: "Demo")
    upload_to_testflight
  end
end
