name: Fastlane
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Provisioning profile
        run: fastlane sigh
      - name: Release beta
        run: fastlane beta
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
