name: Fastlane
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Appstore Connect API key
        run: |
          echo "$APPSTORE_CONNECT_API_KEY" > AuthKey_VG8XUGYMD6.p8.b64
          base64 -d -i AuthKey_VG8XUGYMD6.p8.b64 > AuthKey_VG8XUGYMD6.p8
        env:
          APPSTORE_CONNECT_API_KEY: ${{ secrets.APPSTORE_CONNECT_API_KEY }}
      - name: Build
        run: fastlane connect
      - name: Release beta
        run: fastlane beta
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
