name: Fastlane
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: fastlane beta
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
